/* 50 cybersecurity questions. Each: { question, options[4], answerIndex } */

// I am keeping this in a single var to avoid ESM/CJS issues on github
var QUIZ_QUESTIONS = [
  { question: "What does MFA stand for?", options: ["Multi-Factor Authentication", "Multi-File Access", "Master File Agreement", "Managed Firewall Access"], answerIndex: 0 },
  { question: "A strong password should include:", options: ["Only lowercase letters", "Personal info", "Mix of letters, numbers, symbols", "Common words"], answerIndex: 2 },
  { question: "Phishing is:", options: ["A firewall", "Tricking users to reveal info", "Encrypting data", "A backup method"], answerIndex: 1 },
  { question: "HTTPS primarily provides:", options: ["Power saving", "Faster internet", "Encrypted communication", "Unlimited data"], answerIndex: 2 },
  { question: "Which is an example of PII?", options: ["Favorite color", "IP address", "Email and SSN", "Browser type"], answerIndex: 2 },
  { question: "Ransomware typically:", options: ["Deletes RAM", "Encrypts files for payment", "Speeds up PCs", "Installs drivers"], answerIndex: 1 },
  { question: "The least privilege principle means:", options: ["Everyone admin", "No passwords", "Only necessary access", "Shared accounts"], answerIndex: 2 },
  { question: "Public Wi‑Fi risks include:", options: ["Battery drain", "Shoulder surfing", "Man‑in‑the‑middle attacks", "Faster speeds"], answerIndex: 2 },
  { question: "A VPN helps by:", options: ["Blocking ads", "Hiding browsing and encrypting traffic", "Fixing malware", "Eliminating passwords"], answerIndex: 1 },
  { question: "Two common phishing indicators:", options: ["Perfect grammar, known domain", "Urgency, suspicious links", "HTTPS padlock", "Personalized greeting"], answerIndex: 1 },
  { question: "Which is a secure password example?", options: ["Password123", "letmein", "T!ger_7!Lake", "123456"], answerIndex: 2 },
  { question: "Social engineering targets:", options: ["Only servers", "Human psychology", "Only networks", "Only code"], answerIndex: 1 },
  { question: "Malware short for:", options: ["Male ware", "Malicious software", "Manual ware", "Managed software"], answerIndex: 1 },
  { question: "Which is safest to click?", options: ["Unknown attachment", "Link from stranger", "Bank email link", "URL you typed yourself"], answerIndex: 3 },
  { question: "Patch management is:", options: ["Cable sorting", "Applying updates and fixes", "Encrypting disks", "Managing printers"], answerIndex: 1 },
  { question: "2FA commonly uses:", options: ["Username + name", "Password + token/app code", "Two passwords", "Email only"], answerIndex: 1 },
  { question: "Strong PIN length recommended:", options: ["2", "4", "6+", "3"], answerIndex: 2 },
  { question: "What is a firewall?", options: ["Physical wall", "Traffic filter between networks", "Backup device", "Battery"], answerIndex: 1 },
  { question: "Should you reuse passwords?", options: ["Yes", "Only for social", "No, use unique per site", "Only at work"], answerIndex: 2 },
  { question: "Password managers help by:", options: ["Storing strong unique passwords", "Making them shorter", "Sharing with friends", "Removing 2FA"], answerIndex: 0 },
  { question: "Data encryption protects:", options: ["Data at rest and in transit", "Only photos", "Only emails", "Only devices"], answerIndex: 0 },
  { question: "Should software auto‑update be enabled?", options: ["Never", "Only games", "Often yes for security", "Only phones"], answerIndex: 2 },
  { question: "If you suspect phishing:", options: ["Reply quickly", "Click to verify", "Report and delete", "Forward to everyone"], answerIndex: 2 },
  { question: "Public USB charging risks:", options: ["Juice jacking", "Overheating", "Faster charging", "None"], answerIndex: 0 },
  { question: "What is spear phishing?", options: ["Random spam", "Targeted phishing at specific person/org", "SMS only", "Phone scam"], answerIndex: 1 },
  { question: "Zero‑day means:", options: ["Patch available", "Vulnerability not yet known to vendor", "Old exploit", "Hardware issue"], answerIndex: 1 },
  { question: "Secure Wi‑Fi uses:", options: ["WEP", "Open", "WPA2/WPA3", "No password"], answerIndex: 2 },
  { question: "Should you cover your webcam?", options: ["Never", "Optional privacy measure", "Breaks the cam", "Illegal"], answerIndex: 1 },
  { question: "Fake software updates are often:", options: ["Social engineering", "Hardware faults", "ISP errors", "DDoS"], answerIndex: 0 },
  { question: "DDoS stands for:", options: ["Direct Deploy on Server", "Distributed Denial of Service", "Data Dump on Site", "Disk Damage on System"], answerIndex: 1 },
  { question: "Which is safer message?", options: ["Unsolicited OTP request", "Bank asks password", "Friend urgent crypto", "Known contact on usual channel"], answerIndex: 3 },
  { question: "Backup rule often recommended:", options: ["1‑1‑1", "3‑2‑1 backups", "2‑3‑1", "1‑2‑3"], answerIndex: 1 },
  { question: "Dumpster diving is:", options: ["Recycling", "Finding sensitive data in trash", "Network scan", "Firmware update"], answerIndex: 1 },
  { question: "Should you root/jailbreak?", options: ["Yes for fun", "Only to remove 2FA", "Avoid due to risk", "Always"], answerIndex: 2 },
  { question: "What is a CVE?", options: ["Cloud Virtual Engine", "Common Vulnerabilities and Exposures ID", "Cyber Virus Event", "Core Version Entry"], answerIndex: 1 },
  { question: "Secure physical desk practice:", options: ["Write passwords on sticky notes", "Lock screen when away", "Share badges", "Leave laptop open"], answerIndex: 1 },
  { question: "Pharming attack targets:", options: ["DNS redirection", "CPU cooling", "Screen brightness", "Battery"], answerIndex: 0 },
  { question: "What is sandboxing?", options: ["Beach time", "Isolating apps to limit impact", "Encrypting CPU", "Cooling system"], answerIndex: 1 },
  { question: "SMishing is phishing via:", options: ["Email", "SMS/text", "Phone call", "Browser"], answerIndex: 1 },
  { question: "Vishing is phishing via:", options: ["Video call", "Voice call", "VR", "VPN"], answerIndex: 1 },
  { question: "If device lost/stolen first step:", options: ["Panic", "Post online", "Remote lock/wipe and change passwords", "Ignore"], answerIndex: 2 },
  { question: "Which file types are risky to open?", options: [".exe, .scr, unknown", ".txt only", "Your own notes", "Calendar files"], answerIndex: 0 },
  { question: "Browser extension safety:", options: ["Install many", "Check permissions and reviews", "Unknown sources ok", "Always trusted"], answerIndex: 1 },
  { question: "Certificate warning in browser means:", options: ["Everything fine", "Possible MITM or misconfig", "Lower battery", "Faster site"], answerIndex: 1 },
  { question: "What is brute force attack?", options: ["Guessing passwords repeatedly", "Physical force", "DoS", "Phishing"], answerIndex: 0 },
  { question: "Salting passwords means:", options: ["Adding table salt", "Adding random data before hashing", "Encrypting emails", "Peppering food"], answerIndex: 1 },
  { question: "Public key is used to:", options: ["Decrypt only", "Encrypt or verify signatures", "Cook", "Format disk"], answerIndex: 1 },
  { question: "Private key should be:", options: ["Shared widely", "Stored securely and never shared", "Printed on wall", "Emailed to self"], answerIndex: 1 },
  { question: "Secure disposal of drives:", options: ["Trash can", "Wipe/cryptographic erase", "Gift to stranger", "Leave at desk"], answerIndex: 1 },
  { question: "What is least trustworthy link?", options: ["Misspelled domain", "Known HTTPS site", "Official store", "Direct company URL"], answerIndex: 0 },
  { question: "Bug bounty programs are for:", options: ["Punishing users", "Reporting security bugs for reward", "Marketing", "Free hosting"], answerIndex: 1 },
  { question: "SaaS account hardening includes:", options: ["Disable 2FA", "Use SSO/MFA, strong passwords", "Share logins", "Public repos for secrets"], answerIndex: 1 },
  { question: "What does VPN stand for?", options: ["Virtual Private Network", "Very Personal Notebook", "Verified Password Node", "Video Protocol Net"], answerIndex: 0 },
  { question: "Which is safer: HTTP or HTTPS?", options: ["HTTP", "HTTPS", "Both equal", "Neither"], answerIndex: 1 },
  { question: "Should you click pop-up ads?", options: ["Yes, always", "Only if shiny", "No, they may be malicious", "Only on weekends"], answerIndex: 2 },
  { question: "Which is a type of malware?", options: ["Trojan", "Spreadsheet", "Keyboard", "Monitor"], answerIndex: 0 },
  { question: "Best way to store backups?", options: ["Only same device", "Multiple locations", "No backups", "On sticky notes"], answerIndex: 1 },
  { question: "Which is most secure Wi-Fi password?", options: ["12345678", "mypassword", "Q$9bT7!vL2", "homewifi"], answerIndex: 2 },
  { question: "Phishing emails often include:", options: ["Urgent threats", "Random fonts", "Good deals", "All of the above"], answerIndex: 3 },
  { question: "A Trojan horse is:", options: ["Malware disguised as legit software", "Firewall", "Encryption method", "Backup tool"], answerIndex: 0 },
  { question: "Which device security feature is biometric?", options: ["PIN", "Face ID", "Password", "Pattern"], answerIndex: 1 },
  { question: "What is shoulder surfing?", options: ["Watching someone’s screen/password", "Surfing internet", "Phishing by SMS", "Ransomware"], answerIndex: 0 },
  { question: "Why update apps?", options: ["Fix bugs & security issues", "Change color only", "Break system", "Use less battery"], answerIndex: 0 },
  { question: "Cookies on websites are used for:", options: ["Storing user info", "Encrypting Wi-Fi", "Firewall setup", "Deleting files"], answerIndex: 0 },
  { question: "Which is NOT an authentication factor?", options: ["Something you know", "Something you have", "Something you ate", "Something you are"], answerIndex: 2 },
  { question: "What is spyware?", options: ["Software spying on you", "Antivirus", "Firewall", "Password manager"], answerIndex: 0 },
  { question: "Keylogger records:", options: ["Files", "Keystrokes", "Photos", "Passwords only"], answerIndex: 1 },
  { question: "Cloud storage security tip:", options: ["Use strong password & MFA", "Share link publicly", "Disable updates", "Use default password"], answerIndex: 0 },
  { question: "Cyber hygiene means:", options: ["Clean computer with soap", "Good security habits", "Deleting friends", "Changing keyboard"], answerIndex: 1 },
  { question: "Which is safer file sharing?", options: ["Public forums", "Password-protected link", "Unknown USB", "Social media DM"], answerIndex: 1 },
  { question: "The padlock icon in browser means:", options: ["Encrypted connection", "Free Wi-Fi", "Faster speed", "Virus free"], answerIndex: 0 },
  { question: "Antivirus software helps by:", options: ["Detecting/removing malware", "Making battery better", "Upgrading RAM", "Installing drivers"], answerIndex: 0 },
  { question: "Botnets are:", options: ["Networks of infected devices", "Wi-Fi boosters", "Backup servers", "Encryption methods"], answerIndex: 0 },
  { question: "Best practice for USB drives:", options: ["Scan before opening", "Plug into all PCs", "Share with strangers", "Ignore antivirus"], answerIndex: 0 },
  { question: "Cyberbullying is:", options: ["Online harassment", "Firewall config", "Phishing email", "Malware"], answerIndex: 0 },
  { question: "Which is safer app source?", options: ["Official store", "Random site", "Friend’s USB", "Torrent"], answerIndex: 0 },
  { question: "Public Wi-Fi safe use tip:", options: ["Use VPN", "Do banking directly", "Turn off screen lock", "Share passwords"], answerIndex: 0 },
  { question: "Which is a social engineering attack?", options: ["Phishing", "Vishing", "Tailgating", "All of the above"], answerIndex: 3 },
  { question: "Which symbol often marks secure websites?", options: ["Padlock", "Red X", "Lightning bolt", "Wi-Fi bars"], answerIndex: 0 },
  { question: "Which is example of two-factor authentication?", options: ["Password + OTP code", "Two passwords", "Username + password", "PIN only"], answerIndex: 0 },
  { question: "If device gets malware:", options: ["Install antivirus & scan", "Ignore it", "Post online", "Use more apps"], answerIndex: 0 },
  { question: "What is ransomware’s demand?", options: ["Payment to unlock files", "Delete cookies", "Turn off PC", "Upgrade Wi-Fi"], answerIndex: 0 },
  { question: "Firewall filters:", options: ["Network traffic", "Coffee", "RAM", "Screens"], answerIndex: 0 },
  { question: "Safe password reset practice:", options: ["Via official website", "Clicking any email link", "Sharing with friend", "Posting online"], answerIndex: 0 },
  { question: "Which is NOT malware?", options: ["Trojan", "Worm", "Phishing", "Virus"], answerIndex: 2 },
  { question: "Which info should you avoid sharing publicly?", options: ["Birthday", "SSN", "Home address", "All of these"], answerIndex: 3 },
  { question: "Which is a phishing attempt?", options: ["Email from bank asking password", "Bank’s official app", "Typing URL directly", "Phone contacts"], answerIndex: 0 },
  { question: "What is tailgating in security?", options: ["Following someone into secure area", "Slow Wi-Fi", "Firewall issue", "Phishing SMS"], answerIndex: 0 },
  { question: "Two best practices for mobile security:", options: ["Update OS & use lock screen", "Disable lock & auto-update", "Install random apps", "Ignore permissions"], answerIndex: 0 },
  { question: "What is identity theft?", options: ["Stealing personal info to impersonate", "Losing wallet only", "Buying new phone", "Changing nickname"], answerIndex: 0 },
  { question: "What is a password spray attack?", options: ["Trying common passwords on many accounts", "Deleting all passwords", "Encrypting data", "Wiping drives"], answerIndex: 0 },
  { question: "Which is safer: long or short password?", options: ["Short", "Long", "Both same", "Depends on color"], answerIndex: 1 },
  { question: "What is MFA?", options: ["Multi-Factor Authentication", "Multiple Friends Access", "Main Frame Authorization", "Multi File Action"], answerIndex: 0 },
  { question: "Social media security tip:", options: ["Limit personal info shared", "Post all details", "Share password", "Disable privacy"], answerIndex: 0 },
  { question: "Safe software downloads are from:", options: ["Official websites", "Unknown forums", "Random ads", "Torrent"], answerIndex: 0 },
  { question: "What is pharming?", options: ["Redirecting users to fake websites", "Growing crops online", "Phishing via SMS", "Blocking antivirus"], answerIndex: 0 },
  { question: "Brute force attacks try:", options: ["All password combos", "Only one guess", "No passwords", "Antivirus scans"], answerIndex: 0 },
  { question: "Which is a secure browsing habit?", options: ["Check padlock & URL", "Click all links", "Disable updates", "Ignore warnings"], answerIndex: 0 },
  { question: "Best reaction to suspicious link:", options: ["Don’t click, verify source", "Click to test", "Forward widely", "Save to USB"], answerIndex: 0 },
  { question: "If phone infected with malware:", options: ["Factory reset if needed", "Ignore it", "Disable charging", "Use random apps"], answerIndex: 0 },
  { question: "What does DLP stand for?", options: ["Data Loss Prevention", "Direct Login Page", "Device Lock Protocol", "Disk Level Protection"], answerIndex: 0 },
  { question: "Why avoid public computers for banking?", options: ["They may have keyloggers", "They’re faster", "They’re bigger", "They’re free"], answerIndex: 0 },
  { question: "Best response to scam call?", options: ["Hang up, don’t share info", "Share passwords", "Record and post online", "Send money"], answerIndex: 0 },
  { question: "UCC stands for", options: ["UiTM Cyberunit Club", "Ultimate Cybersecurity Club", "UiTM Cyberheroes Club", "UiTM Cybersecurity Club"], answerIndex: 0 }
];



